import { useEffect } from "react";
import { useLocation, useNavigate, Navigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Download, Home } from "lucide-react";

/* =======================
   TYPES
======================= */
interface Answer {
  question: string;
  answer: string;
}

interface LocationState {
  answers: Answer[];
}

/* =======================
   COMPONENT
======================= */
export default function ItineraryPage() {
  const location = useLocation();
  const navigate = useNavigate();
  const state = location.state as LocationState | null;

  /* 🔒 SAFETY */
  if (!state || !state.answers || state.answers.length === 0) {
    return <Navigate to="/" replace />;
  }

  useEffect(() => {
    document.title = "Your Personalized Sri Lanka Itinerary";
  }, []);

  const downloadPDF = () => {
    window.print();
  };

  return (
    <main className="min-h-screen bg-background px-6 py-14 print:px-0 print:py-0">
      {/* ================= ACTION BAR (HIDDEN IN PDF) ================= */}
      <div className="pdf-actions max-w-3xl mx-auto flex justify-between mb-8 print:hidden">
        <Button
          variant="outline"
          onClick={() => navigate("/")}
          className="flex items-center gap-2"
        >
          <Home size={16} />
          Return Home
        </Button>

        <Button
          className="bg-orange-500 hover:bg-orange-600 flex items-center gap-2"
          onClick={downloadPDF}
        >
          <Download size={16} />
          Download PDF
        </Button>
      </div>

      {/* ================= HEADER ================= */}
      <header className="text-center mb-14 print:mb-10">
        <h1 className="text-4xl font-serif font-semibold tracking-tight">
          Your Personalized Sri Lanka Itinerary
        </h1>
        <p className="mt-3 text-muted-foreground max-w-xl mx-auto">
          Designed around your preferences to create a seamless and memorable journey
        </p>
      </header>

      {/* ================= CONTENT ================= */}
      <section className="pdf-card max-w-3xl mx-auto bg-card shadow-xl rounded-3xl p-10 print:shadow-none">
        {state.answers.map((item, index) => (
          <ItineraryItem
            key={index}
            index={index + 1}
            question={item.question}
            answer={item.answer}
          />
        ))}
      </section>

      {/* ================= FOOTER ================= */}
      <footer className="pdf-footer mt-20 text-center">
        Generated by <strong>Lanka Vacations</strong>
      </footer>
    </main>
  );
}

/* =======================
   ITEM
======================= */
function ItineraryItem({
  index,
  question,
  answer,
}: {
  index: number;
  question: string;
  answer: string;
}) {
  return (
    <div className="mb-8 last:mb-0">
      <div className="flex items-start gap-4">
        <span className="text-sm font-semibold text-primary">
          {index.toString().padStart(2, "0")}
        </span>

        <div>
          <div className="pdf-question mb-1">{question}</div>
          <div className="pdf-answer">{answer}</div>
        </div>
      </div>
    </div>
  );
}
